### ISSUE TITLE
print() and errors no Longer outputs to log, commands execute as normal during server reload

### ISSUE THREAD

**Issue by Wontoon** [evennia/evennia#2083]
#### Brief summary of issue / Description of requested feature:
After updating to the latest version of Evennia (In Windows), I immediately noticed that debug/error information and using print (via it being used in a script/py file) outputs no information to the console log (at least in Windows), and the server log file is no different--after the initial steps, no new information will appear. This behavior is both in Powershell and the command prompt, but not when using the @py command as far as I can tell.

It also appears that while the server is reloading (via the reload command) I was still able to enter commands while it was doing so, unlike before. 

#### Steps to reproduce the issue / Reasons for adding feature:

--for the Log issue---
1. In your script file, use print() or intentionally write code that causes a runtime error.
2. The output of the error or of print() will not appear in the console log or server log file.

---for the command issue---
1. Use @reload
2. While the server is reloading, use any command.
(This one appears to be the nastier of the two, as it can potentially cause problems)

#### Error output / Expected result of feature

The expected result is output in the log window (and not having commands run during server reload). I don't have much to go by on my end, but I recall there being mention of a fix regarding a "stop" command being sent to the server or something along those lines; mayhap that may be somewhat related?

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

Current evennia version: 0.9.0 (rev 10a6685), master branch

**Comment by Griatch** [comment]
... So should this be closed or open ?

**Comment by kovitikus** [comment]
My server log is only 2,050KB and nothing will print to the log either.
I've been using my server recently, but the server.log stopped having anything in it since September 28th, 2019.

I'm on Win10 and here is the command I used to test the print, which resulted in the caller.msg showing up in game, but nothing printed to the log.
https://paste.ofcode.org/yk2mGeuKTD7MZMJqs82XGe

**Comment by RianeNelson** [comment]
I had the same issue when trying to print. 

Code: https://pastebin.com/rf3xkBp0
I made the associated rooms, ran `evennia reload -l` from console. Walked between the rooms and did `evennia reload -l` again. Checked the server log and nothing. It only shows server restarts.

**Comment by Griatch** [comment]
OK, maybe it's a py3 regression of some kind that is unique to Windows. Direct printing is only intended for quick debugging, but it should be fixed nevertheless. For now, use the logger instead: 

```
from evennia import logger

# ....

logger.log_msg("text to print") 
```

**Comment by kovitikus** [comment]
Still nothing. Despite spamming my test command several times. The ingame caller.msg still shows up, but my server.log file in my D:\muddev\hecate\server\logs directory still shows nothing new since Sept 28th, 2019.  

Yes, I did import logger from evennia as instructed.

```py
class CmdTest(Command):
    key = 'testy'

    def func(self):
        caller = self.caller
        # caller.msg("This should be an image!")
        # caller.msg(image="https://i.imgur.com/2Wo1BpT.png")
        # caller.msg(video="https://youtu.be/YUOxwynb9UU")
        # caller.msg(video="https://vimeo.com/358147193")
        caller.msg("Printing something to the log file!")
        logger.log_msg("Something to the log file!!")
```

**Comment by Griatch** [comment]
@kovitikus That is more concerning. You get no server logs at all?

**Comment by kovitikus** [comment]
Nothing at all.

[server.log](https://github.com/evennia/evennia/files/4433212/server.log)

**Comment by kovitikus** [comment]
Ok, I deleted my old server.log file (well, changed the extension to .old) and shut down Evennia and started it fresh again. Evennia of course made a new server.log file. 
This time both print and error logging worked with my command.

[server.log](https://github.com/evennia/evennia/files/4433220/server.log)
```
class CmdTest(Command):
    key = 'testy'

    def func(self):
        caller = self.caller
        # caller.msg("This should be an image!")
        # caller.msg(image="https://i.imgur.com/2Wo1BpT.png")
        # caller.msg(video="https://youtu.be/YUOxwynb9UU")
        # caller.msg(video="https://vimeo.com/358147193")
        caller.msg("Printing something to the log file!")
        logger.log_msg("Something to the log file!!")
        print("printing to the log file too!")
```

**Comment by Griatch** [comment]
The working theory is that Windows's CMD.EXE might have a very small buffer. Also, the log file is meant to cycle every week, maybe there is some problem with that on Windows.

**Comment by Griatch** [comment]
I don't know what to do about this except maybe limiting the log file size on Windows ... It's not clear this is the reason however since it happened with a very small log file for @Kovitikus. So if more Windows users could chip in when noticing this, together with their log file size and other info, that would be useful.

**Comment by kovitikus** [comment]
This is still broken. Even after starting a new server.log file, the log didn't cycle like you said it should and now it won't log anything again.

**Comment by Griatch** [comment]
@kovitikus I wonder if it could be tied to anti-virus software that has been reported as an issue on Windows in the past. Maybe it's blocking Evennia from creating a new file (that is, from rotating the log file)? May be worth to turn off or add an exception in your antivirus for Evennia to see if that helps.

**Comment by Griatch** [comment]
@kovitikus Did disabling anti-virus have any effect on this?

**Comment by kovitikus** [comment]
I don't use anti-virus (even the built in Win10 one is disabled) and the log is still dying on me. Most recent log just died on the 31st of August 2020 and I dunno if that has anything to do with it or it finally hit the same spot all the others did.

**Comment by Griatch** [comment]
So this is still a mystery on Windows then :) I wonder if running under the Linux-for-Windows subsystem would cause the same effect.

**Comment by kovitikus** [comment]
So it turns out there's a real-time protection against malware and such that can't be turned off except for a short period. I'm going to try and add my game folder to the exceptions and see if it helps.

**Comment by kovitikus** [comment]
Despite having my project folder excluded from Microsoft Defender Antivirus scans, I took a month of break and came back to the log no longer functioning. The last entry was `September 28th, 2020` and I attempted to work on my project again on `November 3rd, 2020`. Nothing was showing up in the log upon my return and I was once again forced to delete it and start a new log.

**Comment by davewiththenicehat** [comment]
If you are using Win10 Pro you can permanently disable the antivirus in gpedit.msc
https://www.windowscentral.com/how-permanently-disable-windows-defender-antivirus-windows-10

I have a bare metal windows data recovery system that has to have no antivirus.

**Comment by kovitikus** [comment]
Ok, I've been working diligently on my project for the past several days and the last entry in the log was at:

`20-11-30 20:39:19-05 Server successfully reloaded.`

Despite the fact that I've been using it quite a bit in the past day since then.

This leads me to believe that maybe it has something to do with the month transitioning into the new month? My log ended at 144 KB in size and 2052 lines in length, but I don't feel like either of those are the issue.

All of my previous attempts at tracking this issue have been after I used Evennia for a bit and then took a hiatus, so I could never pinpoint this transition in months. I could still be wrong about this, but I think it's worth considering as a reason for this behavior.

I didn't fully disable my antivirus as Dave suggested. It's not worth doing something like that. If this doesn't get fixed, then I'll just simply continue to delete the log and start a new one manually.

**Comment by Griatch** [comment]
@kovitikus Hm, it's an interesting coincidence but I don't think the log cares about the actual date but only counts 7 days until rotation and/or too big log-size. It's worth to double-check that though.

**Comment by kovitikus** [comment]
I've been reloading a ton, so I know for absolute certain that the log stopped working.

**Comment by kovitikus** [comment]
Zude from Discord informed me that he also had issues with his log dying. His last entry was on the night of November 29th, 2020. [log_a.txt](https://github.com/evennia/evennia/files/5634997/log_a.txt)

He says he isn't entirely certain if he used the server on the 30th of November, but his best guess is that he didn't touch it.

Mounting evidence that this seems to be a pattern of the month changing over from one to the next.

**Comment by blackmonkey** [comment]
Don't know whether I met the same issue as yours. But I found that the server.log is not rotated once it is bigger than 1MB. My current version:
```
    Evennia 0.9.0 (rev 2603e7d26) (rev 2603e7d26)
    OS: nt
    Python: 3.7.0
    Twisted: 19.10.0
    Django: 2.2.13
```
To reproduce the issue, just dump a string of 1MB into log:
```python
from evennia.utils.utils import logger

logger.log_info('=' * 1048576)
```

**Comment by Griatch** [comment]
@blackmonkey Thanks for the further analysis of this; since this is appears to be a Windows-only issue, it's not obvious where to start but that does narrow it down a lot. Maybe one needs to do the file operation in some other way.

**Comment by kovitikus** [comment]
Once again my `server.log` died on me as the month transitioned into the new one. The last entries are from March 31st near the end of the day, despite having had activity on both April 1st and April 2nd that I know should have generated log entries, including tracebacks just a few minutes ago.

**Comment by fariparedes** [comment]
Also had this issue a few times before, also on Windows 10. Clearing the log file seems to resolve it.

**Comment by kovitikus** [comment]
Still the same issue with it dying on the month change. I've paid attention to enough of these months now that I'm absolutely certain it's a thing.

My log went strong from April 4th to April 29th (I haven't done anything since then, but the log definitely died as I just checked.)

Despite my lack of precision on this matter, regarding checking the log exactly at the end, there's no doubt in my mind that I'm 100% correct on the month change killing it.

IIRC the log is supposed to rotate weekly, which it does not. It just fills up until the month is over and then dies.

[server.log](https://github.com/evennia/evennia/files/6445613/server.log)

**Comment by InspectorCaracal** [comment]
I've done some research and testing and it seems as though this is a combination of `os.rename` not working on Windows and the maximum log file size.

Evennia uses Twisted logging, which remarks [here](https://github.com/twisted/twisted/blob/trunk/src/twisted/python/logfile.py#L127) and [here](https://docs.twistedmatrix.com/en/stable/api/twisted.python.filepath.FilePath.html#setContent) on the problems with `rename` and Windows, which means that when the server tries to rename the existing server.log and start writing to a new one, the rename fails silently and, since the target log file to write is always server.log, it continues writing to it as normal.

However, when the log file exceeds the log file size limit, that _also_ fails silently and doesn't write anything. I tested this part by first setting up a clean install of evennia v0.9.5 in Windows, then doing the following:

* I started the server, stopped it, and checked the log. It logged correctly.
* I pasted 3MB of text into the log file, closed the log, started the server again, and stopped it. No new lines were logged.
* I went into Evennia's code and commented out the size check in `WeeklyLogFile.shouldRotate` and repeated the start/stop. It successfully logged to the existing file.

That said, I can't figure out what is preventing it from continuing to write to the file after failing to rotate for reaching maximum size the same as it does when it reaches maximum age. The size check and the age check are both done only in `shouldRotate`.

**Comment by fariparedes** [comment]
That tracks with the fact that it works perfectly fine on my Unix prod server but not my Windows test server.

**Comment by InspectorCaracal** [comment]
WAIT. Okay everything I said in my last comment is still true but I figured out something important and surprisingly confirms the end-of-month correlation.

Here is the overloaded `shouldRotate`
```
     def shouldRotate(self):
        """Rotate when the date has changed since last write"""
        # all dates here are tuples (year, month, day)
        now = self.toDate()
        then = self.lastDate
        return (
            now[0] > then[0]
            or now[1] > then[1]
            or now[2] > (then[2] + self.day_rotation)
            or self.size >= self.max_size
        )
```

This will return true in the following situations:
* The year is different between `now` and `then`.
* The month is different between `now` and `then`.
* The date is *more than 7 days* different between `now` and `then`
* The size exceeds the max size.

Additionally, `lastDate` is set on *every write* to the log.

This means that `shouldRotate` will return true and attempt to rotate (and, in Windows, fail) only in the following situations:
* The year has changed since the last log entry
* The month has changed since the last log entry
* It has been more than 7 days since the last log entry
* The file size is too big

This means that if your server was active and running for an entire month with frequent logging, it wouldn't attempt to rotate until the new month, because it requires a _gap_ of 7 days to return True.

**Comment by Griatch** [comment]
@InspectorCaracal That is interesting and sounds like a plausible explanation, including for the strange 30-day delay. :clap: 
So it would seem one would need to add some sort of custom replacement for `os.rename` for Windows only ... maybe there's some third-party solution for it, or one could try to emulate it with a combination of `mv` operations. Worst case I guess one could read and save a new file in Python, but _surely_ Windows must have some suitable tools for performing basic file operations ... ? :raised_eyebrow:

**Comment by InspectorCaracal** [comment]
I've done some more research this evening and it looks like Python and Windows file management is a bit of a Problem with a Capital P, due to the way Windows handles file deletion and permissions.

I've tried a variety of approaches and while I can "move" the log file to a new location in `rotate` by using `shutil.move`, it's actually just a copy because the deletion of the original never happens. Even explicitly using `os.remove` doesn't get rid of it. Apparently there's some sort of delay or cache in Windows file handles/operations so you need to give it time to be marked as closed after closing it, and hope that no AV or indexing software grabs it in the meantime?

At this point I'd suggest leaving the rotate code as-is but noting in the documentation that Windows installs should use their own log rotation solutions, as it looks like it's a systemic OS support issue.

**Comment by Griatch** [comment]
That sounds ... bizarre. We should not require Windows users to use their own log rotation. Worst case, we'll read the to-rotate log file in Python, write the contents to the 'rotated' new file and wipe the contents of the current file so one can keep writing to it. But I can't imagine this is not a solved problem even on Windows; maybe there's some process or third-party solution to use.

**Comment by Griatch** [comment]
I don't really know how to address this on the Windows side, if Windows is really acting up this way. But I've now caught and logged any errors coming from the log rotation failing - so maybe that can give us some log info while not killing the logging entirely (but the log file on Windows could well become very big instead).

**Comment by Griatch** [comment]
Have any Windows users seen any useful log output from this since?

**Comment by Griatch** [comment]
@InspectorCaracal Did you see any of the log messages since those were introduced?

**Comment by InspectorCaracal** [comment]
> @InspectorCaracal Did you see any of the log messages since those were introduced?

Oh, I completely forgot about this issue.

I only use Windows for local dev, so I've never personally run into the issue described involving long-running Windows installs, but I can confirm that when it runs into the file rotation issue in Windows, it no longer fails silently but instead logs a traceback about file permissions. Since this is due to a python-Windows interaction outside of evennia's control, I typically tell people who ask about it on discord to delete or move the file manually.

Here's an example of the usual traceback that was posted to discord:
```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\twisted\application\app.py", line 447, in getApplication
    log.msg("Loaded.")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\twisted\python\threadable.py", line 51, in sync
    return function(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\twisted\python\log.py", line 276, in msg
    _publishNew(self._publishPublisher, actualEventDict, textFromEventDict)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\twisted\logger\_legacy.py", line 147, in publishToNewObserver
    observer(eventDict)
--- <exception caught here> ---
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\twisted\logger\_observer.py", line 81, in __call__
    observer(event)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\twisted\logger\_file.py", line 50, in __call__
    self._outFile.write(text)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\evennia\utils\logger.py", line 363, in write
    logfile.BaseLogFile.write(self, data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\twisted\python\logfile.py", line 104, in write
    self._file.write(data)
builtins.ValueError: I/O operation on closed file
```

If the initially described month thing was fixed then I think this issue can be closed.

**Comment by Griatch** [comment]
Thanks. That's useful and says something about the sequence of events.
