### ISSUE TITLE
[BUG] Lots of blank lines in Character Creator Contrib

### ISSUE THREAD

**Issue by 0bviouSquirre1** [evennia/evennia#3024]
#### Describe the bug
When using the Character Creator contrib fresh out of the box, at the step where you choose a name, the name check pauses for a moment, then outputs a whole screen of blank lines. I can scroll back up to see that it's finished, and can continue on after that.

#### To Reproduce
1. Install Character Creator Contrib
2. Run evennia and create a new character
3. Progress through and enter a name for your character

#### Expected behavior
The output should appear on the screen with no extraneous blank space.

#### Environment, Evennia version, OS etc
Evennia 1.0-dev
OS: posix (Ubuntu 22.04.1 LTS)
Python: 3.11.0rc1
Twisted: 22.10.0
Django: 4.1.3

**Comment by InspectorCaracal** [comment]
This is an issue with EvMenu, not the contrib (see: #3019 ) that was fixed for the current 1.0.1 bugfix release.

**Comment by Griatch** [comment]
Evennia 1.0-dev is not to be used anymore. Work off `main` branch and/or Evennia pypi version 1.0.1.

**Comment by 0bviouSquirre1** [comment]
Turns out I'm still experiencing this in version 1.0.1:

Evennia 1.0.1
OS: posix
Python: 3.11.0rc2
Twisted: 22.10.0
Django: 4.1.4

Fresh install earlier today on a fresh install of Ubuntu.

**Comment by InspectorCaracal** [comment]
I verified that this isn't some sort of generic `_default` regression, so it must be something less obvious that the chargen menu is doing which is resulting in this. I'll investigate further.
